version: 2
jobs:
  build:
    docker:
      - image: andthensome/alpine-hugo-git-bash
    branches:
      only:
        main
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
    
